"""sync manual portfolio history table

Revision ID: d842caeda136
Revises: 0f71014c9713
Create Date: 2026-03-27 00:24:28.104222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd842caeda136'
down_revision: Union[str, None] = '0f71014c9713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('cash_flow', sa.Float(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('market_sentiments')
    op.create_index(op.f('ix_news_articles_id'), 'news_articles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_articles_id'), table_name='news_articles')
    op.create_table('market_sentiments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('context_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('market_sentiments_asset_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('market_sentiments_pkey'))
    )
    op.drop_table('portfolio_history')
    # ### end Alembic commands ###
