# app/agents/state.py
from typing import TypedDict, List, Annotated
import operator

# The 'Annotated' and 'operator.add' tells LangGraph how to update the state.
# Instead of overwriting the list of messages, it appends to them.
class AgentState(TypedDict):
    # Inputs (What we pass into the graph to start it)
    user_id: int
    rra_coefficient: float
    investment_amount: float
    
    # Agent Scratchpads (Where workers drop their research)
    fundamental_analysis: str
    sentiment_analysis: str
    valuation_analysis: str
    
    # Internal routing (Supervisor uses this to decide who goes next)
    next_agent: str
    
    # The final output generated by the Senior Portfolio Agent
    # This will be passed to your Markowitz MVO algorithm
    approved_asset_classes: List[str]
    optimization_constraints: dict 
    
    # A running log of all tool calls and LLM thoughts
    messages: Annotated[list, operator.add]