# app/api/v1/endpoints/auth.py
from datetime import timedelta
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import OAuth2PasswordRequestForm
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.models.user import User, RiskProfile
from app.core.security import (
    verify_password, 
    get_password_hash, 
    create_access_token, 
    ACCESS_TOKEN_EXPIRE_MINUTES
)
from app.schemas.user import UserCreate, UserResponse 

router = APIRouter()

@router.post("/signup", response_model=UserResponse, status_code=status.HTTP_201_CREATED)
def create_user(user_in: UserCreate, db: Session = Depends(get_db)):
    # 1. Check if the email is already registered in Supabase
    existing_user = db.query(User).filter(User.email == user_in.email).first()
    if existing_user:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Email already registered"
        )
    
    # 2. Hash the password securely
    hashed_pw = get_password_hash(user_in.password)
    
    # 3. Calculate a baseline RRA Coefficient from the questionnaire
    total_score = (
        user_in.risk_answers.time_horizon_score + 
        user_in.risk_answers.liquidity_score + 
        user_in.risk_answers.loss_tolerance_score
    )
    # Placeholder algorithm: reverse scales the 3-15 score into a 2.0 - 10.0 coefficient
    calculated_rra = max(2.0, 12.0 - (total_score * 0.66))

    # 4. Create the User record in Supabase
    new_user = User(
        email=user_in.email,
        hashed_password=hashed_pw,
        full_name=user_in.full_name,
        rra_coefficient=calculated_rra
    )
    db.add(new_user)
    db.commit() 
    db.refresh(new_user) # Fetches the new ID generated by Postgres
    
    # 5. Create the linked Risk Profile record
    new_risk_profile = RiskProfile(
        user_id=new_user.id,
        time_horizon_score=user_in.risk_answers.time_horizon_score,
        liquidity_score=user_in.risk_answers.liquidity_score,
        loss_tolerance_score=user_in.risk_answers.loss_tolerance_score
    )
    db.add(new_risk_profile)
    db.commit()

    # Returns the user data (Pydantic formats it to match UserResponse)
    return new_user

@router.post("/token")
async def login_for_access_token(
    form_data: OAuth2PasswordRequestForm = Depends(),
    db: Session = Depends(get_db) 
):
    # 1. Find the user in Supabase by their email
    user = db.query(User).filter(User.email == form_data.username).first()

    # 2. Verify they exist and the passwords match
    if not user or not verify_password(form_data.password, user.hashed_password):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect email or password",
            headers={"WWW-Authenticate": "Bearer"},
        )

    # 3. Generate the JWT access token
    access_token_expires = timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    access_token = create_access_token(
        data={"sub": user.email}, 
        expires_delta=access_token_expires
    )

    return {
        "access_token": access_token, 
        "token_type": "bearer"
    }